project:
  type: website

website:
  title: "Engineering Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Embedded Systems
        menu: 
          - href: labs/lab1/lab1.qmd
            text: Lab 1
          - href: labs/lab2/lab2.qmd
            text: Lab 2
          - href: labs/lab3/lab3.qmd
            text: Lab 3
          - href: labs/lab4/lab4.qmd
            text: Lab 4
          - href: labs/lab5/lab5.qmd
            text: Lab 5
          - href: labs/lab6/lab6.qmd
            text: Lab 6
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



